name: 'postgresql_dbt'
version: '1.0.0'
config-version: 2

profile: 'postgresql_dbt'

model-paths: ["postgresql_dbt/models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  postgresql_dbt:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
