version: 2

sources:
  - name: projeto_paises
    schema: public  # ou o schema correto do seu banco, conforme definido no profiles.yml
    tables:
      - name: fato_pais
        description: "Tabela com dados históricos de países (fonte alternativa)"
        columns:
          - name: nome_resumido
            description: "Nome resumido conforme IBGE"
          - name: nome
            description: "Nome oficial do país"
          - name: nome_oficial
            description: "nome_oficial do país"
          - name: capital
            description: "capital geográfica"
          - name: regiao
            description: "região geográfica"
          - name: subregiao
            description: "subregiao"
          - name: populacao
            description: "população"
          - name: area_km2
            description: "tamanho"
          - name: idiomas
            description: "idioma"
          - name: moedas
            description: "moeda do pais"
          - name: bandeira_url
            description: "bandeira do pais"
          - name: data_carga
            description: "Data da carga no banco"